# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrpcion', models.TextField()),
                ('requisitos', models.CharField(max_length=100)),
                ('syllabus', models.TextField()),
                ('politicas', models.TextField()),
            ],
        ),
    ]
