# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descrpcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='syllabus',
        ),
    ]
