# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_auto_20170222_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('descrpcion', models.TextField()),
            ],
        ),
    ]
